version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vanity-number"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-c4qs733qc3xd"
s3_prefix = "vanity-number"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
